### ISSUE TITLE
Submit to Pelican plugin repository

### ISSUE THREAD

**Issue by kdeldycke** [jrarseneau/pelican-titlecase#1]
May I suggest contributing this plugin to the official Pelican plugin repository ?

**Comment by jrarseneau** [comment]
I'll most likely be contributing this back to the core plugin repository. 

Granted, I feel having a "core" plugin repository kind of defeats the purpose. I understand it's easier to find plugins by integrating them all into a core plugin release, but it makes it difficult for plugin authors to submit pull requests because they tend to not get integrated right away.

**Comment by kdeldycke** [comment]
I agree with you. We should not depends on a central plugin repository.

The thing is the `PLUGIN_PATH` variable in `pelicanconf.py` is not a list, so I can't put a copy of your module alongside the copy of the Pelican central repository.

**Comment by kdeldycke** [comment]
As you can see I've opened an issue on Pelican's side: https://github.com/getpelican/pelican/issues/981

**Comment by kdeldycke** [comment]
We can now close this issue now that Pelican support multiple local plugin paths.

FYI, here's how I now use both `titlecase` and core plugins: https://github.com/kdeldycke/kevin-deldycke-blog/commit/100070ef4367caab37ef188812979b52fa386b46
